local p = require("lush_theme.lavi.palette")

-- Base16 color scheme mapping
-- See: https://github.com/chriskempson/base16/blob/main/styling.md
local colors = {
  base00 = p.dark_bg, -- Default Background
  base01 = p.black, -- Lighter Background
  base02 = p.selection_bg, -- Selection Background
  base03 = p.bright_black, -- Comments
  base04 = p.fg_nc, -- Dark Foreground
  base05 = p.fg, -- Default Foreground
  base06 = p.white, -- Light Foreground
  base07 = p.bright_white, -- Light Background
  base08 = p.red, -- Variables, Diff Deleted
  base09 = p.orange, -- Integers, Constants
  base0A = p.yellow, -- Classes, Search
  base0B = p.green, -- Strings, Diff Inserted
  base0C = p.cyan, -- Regex, Escape
  base0D = p.blue, -- Functions
  base0E = p.magenta, -- Keywords
  base0F = p.blush, -- Deprecated
}

-- Helper to strip # from hex color
local function hex(color)
  return tostring(color):sub(2)
end

-- Transform for contrib/base16/lavi.yaml
local function transform(compiled)
  local lines = {
    "# Auto-generated by build.lua - do not edit manually",
    "# Base16 color scheme for Stylix and other base16 consumers",
    "# See: https://github.com/chriskempson/base16",
    "scheme: Lavi",
    "author: Maddison Hellstrom (https://github.com/b0o)",
    string.format('base00: "%s"', hex(compiled.base00)),
    string.format('base01: "%s"', hex(compiled.base01)),
    string.format('base02: "%s"', hex(compiled.base02)),
    string.format('base03: "%s"', hex(compiled.base03)),
    string.format('base04: "%s"', hex(compiled.base04)),
    string.format('base05: "%s"', hex(compiled.base05)),
    string.format('base06: "%s"', hex(compiled.base06)),
    string.format('base07: "%s"', hex(compiled.base07)),
    string.format('base08: "%s"', hex(compiled.base08)),
    string.format('base09: "%s"', hex(compiled.base09)),
    string.format('base0A: "%s"', hex(compiled.base0A)),
    string.format('base0B: "%s"', hex(compiled.base0B)),
    string.format('base0C: "%s"', hex(compiled.base0C)),
    string.format('base0D: "%s"', hex(compiled.base0D)),
    string.format('base0E: "%s"', hex(compiled.base0E)),
    string.format('base0F: "%s"', hex(compiled.base0F)),
  }
  return lines
end

return {
  colors = colors,
  transform = transform,
}
