local p = require("lush_theme.lavi.palette")
local lavi = require("lush_theme.lavi")
local transforms = require("lush_theme.lavi.transforms")

local colors = {
  useCustom = true,

  -- Title bar: match Normal highlight group
  TitleFore = lavi.Normal.fg,
  TitleBack = lavi.Normal.bg,
  TitleInfo = lavi.Normal.fg,

  -- List items: use Statement for titles (like keywords), softer desc
  NormalTitle = lavi.Statement.fg,
  DimmedTitle = lavi.Comment.fg,
  SelectedTitle = p.cyan.desaturate(10).lighten(50), -- match Function highlight
  NormalDesc = p.velvet, -- soft lavender, not raw green
  DimmedDesc = lavi.Comment.fg,
  SelectedDesc = p.cyan.desaturate(10).lighten(50),

  -- Status: use accent from the theme
  StatusMsg = p.bright_violet.darken(5).desaturate(30),
  PinIndicatorColor = p.cayenne,

  -- Selection borders: match the selected title color
  SelectedBorder = p.cyan.desaturate(10).lighten(50),
  SelectedDescBorder = p.cyan.desaturate(10).lighten(50),

  -- Filter: draw from search/match highlight groups
  FilteredMatch = lavi.Search.fg,
  FilterPrompt = p.yellow.lighten(20).desaturate(20),
  FilterInfo = lavi.Normal.fg,
  FilterText = lavi.Normal.fg,
  FilterCursor = p.orange.desaturate(10).lighten(15),

  -- Help: use Function color for keys, normal for descriptions
  HelpKey = lavi.Function.fg,
  HelpDesc = lavi.Normal.fg,

  -- Pagination
  PageActiveDot = p.matcha,
  PageInactiveDot = lavi.Comment.fg,
  DividerDot = p.cayenne,

  -- Preview
  PreviewedText = lavi.Normal.fg,
  PreviewBorder = lavi.Statement.fg,
}

-- Transform for contrib/clipse/lavi.json
local function transform(compiled)
  return transforms.to_json(compiled)
end

-- Transform for nix/themes/clipse.nix
local function transform_nix(compiled)
  return transforms.to_nix(compiled, {
    header = {
      "Auto-generated by build.lua - do not edit manually",
      "For use with home-manager's services.clipse.theme",
    },
  })
end

return {
  colors = colors,
  transform = transform,
  transform_nix = transform_nix,
}
