local p = require("lush_theme.lavi.palette")
local lavi = require("lush_theme.lavi")
local transforms = require("lush_theme.lavi.transforms")

local colors = {
  useCustom = true,

  -- Title bar
  TitleFore = p.fg_dim,
  TitleBack = lavi.Normal.bg,
  TitleInfo = p.fg_nc,

  -- List items: restrained palette - lavender accent, muted shades for depth
  NormalTitle = p.fg_dim,
  DimmedTitle = p.bright_black,
  SelectedTitle = p.blush,
  NormalDesc = p.fg_nc,
  DimmedDesc = p.bright_black,
  SelectedDesc = p.fg_dim,

  -- Status: soft violet accent
  StatusMsg = p.velvet,
  PinIndicatorColor = p.lavender,

  -- Selection borders: match the selected title color
  SelectedBorder = p.blush,
  SelectedDescBorder = p.bright_black,

  -- Filter: keep cohesive with lavender/blush family
  FilteredMatch = p.blush,
  FilterPrompt = p.fg_dim,
  FilterInfo = p.fg_nc,
  FilterText = p.fg_dim,
  FilterCursor = p.lavender,

  -- Help
  HelpKey = p.velvet,
  HelpDesc = p.fg_nc,

  -- Pagination: shades of the same palette
  PageActiveDot = p.velvet,
  PageInactiveDot = p.bright_black,
  DividerDot = p.med_black,

  -- Preview
  PreviewedText = p.fg_nc,
  PreviewBorder = p.bright_black,
}

-- Transform for contrib/clipse/lavi.json
local function transform(compiled)
  return transforms.to_json(compiled)
end

-- Transform for nix/themes/clipse.nix
local function transform_nix(compiled)
  return transforms.to_nix(compiled, {
    header = {
      "Auto-generated by build.lua - do not edit manually",
      "For use with home-manager's services.clipse.theme",
    },
  })
end

return {
  colors = colors,
  transform = transform,
  transform_nix = transform_nix,
}
