local p = require("lush_theme.lavi.palette")
local transforms = require("lush_theme.lavi.transforms")

-- Colors for foot terminal
local colors = {
  bg = p.bg,
  fg = p.fg,
  cursor_fg = p.cursor_fg,
  cursor_bg = p.cursor_bg,

  -- Normal colors
  black = p.black,
  red = p.red,
  green = p.green,
  yellow = p.yellow,
  blue = p.blue,
  magenta = p.magenta,
  cyan = p.cyan,
  white = p.white,

  -- Bright colors
  bright_black = p.bright_black,
  bright_red = p.bright_red,
  bright_green = p.bright_green,
  bright_yellow = p.bright_yellow,
  bright_blue = p.bright_blue,
  bright_magenta = p.bright_magenta,
  bright_cyan = p.bright_cyan,
  bright_white = p.bright_white,
}

-- Helper to strip # from hex color
local function hex(color)
  return tostring(color):sub(2)
end

-- Transform for contrib/foot/lavi.ini (foot uses no # prefix for colors)
local function transform(compiled)
  local lines = {
    "[cursor]",
    string.format("color=%s %s", hex(compiled.cursor_fg), hex(compiled.cursor_bg)),
    "",
    "[colors]",
    string.format("background=%s", hex(compiled.bg)),
    string.format("foreground=%s", hex(compiled.fg)),
    "",
    string.format("regular0=%s", hex(compiled.black)),
    string.format("regular1=%s", hex(compiled.red)),
    string.format("regular2=%s", hex(compiled.green)),
    string.format("regular3=%s", hex(compiled.yellow)),
    string.format("regular4=%s", hex(compiled.blue)),
    string.format("regular5=%s", hex(compiled.magenta)),
    string.format("regular6=%s", hex(compiled.cyan)),
    string.format("regular7=%s", hex(compiled.white)),
    "",
    string.format("bright0=%s", hex(compiled.bright_black)),
    string.format("bright1=%s", hex(compiled.bright_red)),
    string.format("bright2=%s", hex(compiled.bright_green)),
    string.format("bright3=%s", hex(compiled.bright_yellow)),
    string.format("bright4=%s", hex(compiled.bright_blue)),
    string.format("bright5=%s", hex(compiled.bright_magenta)),
    string.format("bright6=%s", hex(compiled.bright_cyan)),
    string.format("bright7=%s", hex(compiled.bright_white)),
  }
  return lines
end

-- Build the nix structure from compiled colors
-- Note: foot uses space-separated cursor colors and no # prefix
local function build_nix_theme(c)
  return {
    cursor = {
      color = hex(c.cursor_fg) .. " " .. hex(c.cursor_bg),
    },
    colors = {
      background = hex(c.bg),
      foreground = hex(c.fg),
      regular0 = hex(c.black),
      regular1 = hex(c.red),
      regular2 = hex(c.green),
      regular3 = hex(c.yellow),
      regular4 = hex(c.blue),
      regular5 = hex(c.magenta),
      regular6 = hex(c.cyan),
      regular7 = hex(c.white),
      bright0 = hex(c.bright_black),
      bright1 = hex(c.bright_red),
      bright2 = hex(c.bright_green),
      bright3 = hex(c.bright_yellow),
      bright4 = hex(c.bright_blue),
      bright5 = hex(c.bright_magenta),
      bright6 = hex(c.bright_cyan),
      bright7 = hex(c.bright_white),
    },
  }
end

-- Transform for nix/themes/foot.nix
local function transform_nix(compiled)
  local theme = build_nix_theme(compiled)
  return transforms.to_nix(theme, {
    header = {
      "Auto-generated by build.lua - do not edit manually",
      "For use with home-manager's programs.foot.settings",
    },
  })
end

return {
  colors = colors,
  transform = transform,
  transform_nix = transform_nix,
}
