local p = require("lush_theme.lavi.palette")

-- Terminal colors tuned to match the neovim theme's softer aesthetic
-- These are less vibrant than the raw palette colors
local colors = {
  bg = p.dark_bg,
  fg = p.dark_fg,
  selection_fg = p.fg,
  selection_bg = p.selection_bg,
  cursor_fg = p.dark_fg,
  cursor_bg = p.dark_bg,
  split_divider = p.med_black,

  -- Normal colors - slightly muted versions
  black = p.black,
  red = p.red.desaturate(15).darken(5),
  green = p.green.desaturate(25).darken(10),
  yellow = p.yellow.desaturate(10).darken(5),
  blue = p.blue.desaturate(10),
  magenta = p.velvet, -- Use velvet (soft lavender) instead of bright magenta
  cyan = p.cyan.desaturate(20).darken(5),
  white = p.white,

  -- Bright colors - still softer than raw palette
  bright_black = p.bright_black,
  bright_red = p.bright_red.desaturate(10),
  bright_green = p.bright_green.desaturate(20).darken(5),
  bright_yellow = p.bright_yellow.desaturate(10),
  bright_blue = p.bright_blue.desaturate(5),
  bright_magenta = p.bright_magenta.desaturate(15),
  bright_cyan = p.bright_cyan.desaturate(15),
  bright_white = p.bright_white,
}

-- Transform for contrib/ghostty/lavi.conf
local function transform(compiled)
  local lines = {
    string.format("background = %s", compiled.bg),
    string.format("foreground = %s", compiled.fg),
    "",
    string.format("selection-foreground = %s", compiled.selection_fg),
    string.format("selection-background = %s", compiled.selection_bg),
    "",
    string.format("cursor-color = %s", compiled.cursor_fg),
    string.format("cursor-text = %s", compiled.cursor_bg),
    "",
    string.format("split-divider-color = %s", compiled.split_divider),
    "",
    string.format("palette = 0=%s", compiled.black),
    string.format("palette = 1=%s", compiled.red),
    string.format("palette = 2=%s", compiled.green),
    string.format("palette = 3=%s", compiled.yellow),
    string.format("palette = 4=%s", compiled.blue),
    string.format("palette = 5=%s", compiled.magenta),
    string.format("palette = 6=%s", compiled.cyan),
    string.format("palette = 7=%s", compiled.white),
    string.format("palette = 8=%s", compiled.bright_black),
    string.format("palette = 9=%s", compiled.bright_red),
    string.format("palette = 10=%s", compiled.bright_green),
    string.format("palette = 11=%s", compiled.bright_yellow),
    string.format("palette = 12=%s", compiled.bright_blue),
    string.format("palette = 13=%s", compiled.bright_magenta),
    string.format("palette = 14=%s", compiled.bright_cyan),
    string.format("palette = 15=%s", compiled.bright_white),
    "",
    "# vim: set ft=dosini commentstring=#\\ %s:",
  }
  return lines
end

-- Transform for nix/themes/ghostty.nix
local function transform_nix(compiled)
  local lines = {
    "# Auto-generated by build.lua - do not edit manually",
    "{",
  }

  local single_keys = {
    { key = "background", value = compiled.bg },
    { key = "foreground", value = compiled.fg },
    { key = "cursor-color", value = compiled.cursor_fg },
    { key = "cursor-text", value = compiled.cursor_bg },
    { key = "selection-background", value = compiled.selection_bg },
    { key = "selection-foreground", value = compiled.selection_fg },
  }

  for _, item in ipairs(single_keys) do
    -- Remove # prefix for nix
    local hex = tostring(item.value):gsub("^#", "")
    table.insert(lines, string.format('  %s = "%s";', item.key, hex))
  end

  table.insert(lines, "  palette = [")
  local palette_colors = {
    compiled.black,
    compiled.red,
    compiled.green,
    compiled.yellow,
    compiled.blue,
    compiled.magenta,
    compiled.cyan,
    compiled.white,
    compiled.bright_black,
    compiled.bright_red,
    compiled.bright_green,
    compiled.bright_yellow,
    compiled.bright_blue,
    compiled.bright_magenta,
    compiled.bright_cyan,
    compiled.bright_white,
  }
  for i, color in ipairs(palette_colors) do
    table.insert(lines, string.format('    "%d=%s"', i - 1, tostring(color)))
  end
  table.insert(lines, "  ];")
  table.insert(lines, "}")

  return lines
end

return {
  colors = colors,
  transform = transform,
  transform_nix = transform_nix,
}
