local colors = {
  -- PATCH_OPEN
Normal = {fg = "#EDE7FE", bg = "#27223F"},
CmpNormal = {link = "Normal"},
DapUINormal = {link = "Normal"},
QFListNormal = {link = "Normal"},
TelescopeNormal = {link = "Normal"},
ActivePopupBorder = {fg = "#706FB3"},
CmpBorder = {link = "ActivePopupBorder"},
NeogitFloatBorder = {link = "ActivePopupBorder"},
NoiceCmdlinePopupBorder = {link = "ActivePopupBorder"},
TelescopeBorder = {link = "ActivePopupBorder"},
AerialLine = {bg = "#6A5FA5"},
AerialLineNC = {bg = "#463E6F"},
AvanteInlineHint = {fg = "#D2BBFB"},
AvanteReversedSubtitle = {fg = "#8591FF"},
AvanteReversedThirdTitle = {fg = "#FFD68F"},
AvanteReversedTitle = {fg = "#8AF9A6"},
AvanteSubtitle = {fg = "#FFFFFF", bg = "#8591FF"},
AvanteThirdTitle = {fg = "#2E2A37", bg = "#FFD68F"},
AvanteTitle = {fg = "#2E2A37", bg = "#8AF9A6"},
Boolean = {fg = "#6EF2D3"},
NavicIconsBoolean = {link = "Boolean"},
BlinkCmpDocBorder = {link = "CmpBorder"},
BlinkCmpMenuBorder = {link = "CmpBorder"},
BlinkCmpSignatureHelpBorder = {link = "CmpBorder"},
CmpItemAbbr = {fg = "#EDE7FE"},
BlinkCmpLabel = {link = "CmpItemAbbr"},
CmpItemAbbrDeprecated = {fg = "#FF8093", strikethrough = true},
BlinkCmpLabelDeprecated = {link = "CmpItemAbbrDeprecated"},
BlinkCmpLabelMatch = {link = "CmpItemAbbrMatch"},
CmpItemKind = {fg = "#FFFFFF"},
BlinkCmpKind = {link = "CmpItemKind"},
CmpItemKindColor = {fg = "#FFFFFF", bg = "#A3E0CB"},
BlinkCmpKindColor = {link = "CmpItemKindColor"},
CmpItemKindEvent = {fg = "#FFFFFF", bg = "#DDBDFF"},
BlinkCmpKindEvent = {link = "CmpItemKindEvent"},
BlinkCmpKindFile = {link = "CmpItemKindEvent"},
BlinkCmpKindFolder = {link = "CmpItemKindEvent"},
BlinkCmpKindUnit = {link = "CmpItemKindEvent"},
CmpItemKindFile = {link = "CmpItemKindEvent"},
CmpItemKindFolder = {link = "CmpItemKindEvent"},
CmpItemKindUnit = {link = "CmpItemKindEvent"},
CmpItemKindMagic = {fg = "#FFFFFF", bg = "#F9AA86"},
CmpItemKindDictkey = {link = "CmpItemKindMagic"},
CmpItemKindInstance = {link = "CmpItemKindMagic"},
CmpItemKindPath = {link = "CmpItemKindMagic"},
CmpItemKindStatement = {link = "CmpItemKindMagic"},
CmpItemKindMethod = {fg = "#FFFFFF", bg = "#A28BEA"},
BlinkCmpKindConstructor = {link = "CmpItemKindMethod"},
BlinkCmpKindFunction = {link = "CmpItemKindMethod"},
BlinkCmpKindMethod = {link = "CmpItemKindMethod"},
CmpItemKindConstructor = {link = "CmpItemKindMethod"},
CmpItemKindFunction = {link = "CmpItemKindMethod"},
CmpItemKindModule = {fg = "#FFFFFF", bg = "#FFC96B"},
BlinkCmpKindClass = {link = "CmpItemKindModule"},
BlinkCmpKindEnum = {link = "CmpItemKindModule"},
BlinkCmpKindInterface = {link = "CmpItemKindModule"},
BlinkCmpKindModule = {link = "CmpItemKindModule"},
BlinkCmpKindStruct = {link = "CmpItemKindModule"},
CmpItemKindClass = {link = "CmpItemKindModule"},
CmpItemKindEnum = {link = "CmpItemKindModule"},
CmpItemKindInterface = {link = "CmpItemKindModule"},
CmpItemKindStruct = {link = "CmpItemKindModule"},
CmpItemKindOperator = {fg = "#FFFFFF", bg = "#90DAA9"},
BlinkCmpKindKeyword = {link = "CmpItemKindOperator"},
BlinkCmpKindOperator = {link = "CmpItemKindOperator"},
BlinkCmpKindTypeParameter = {link = "CmpItemKindOperator"},
CmpItemKindKeyword = {link = "CmpItemKindOperator"},
CmpItemKindTypeParameter = {link = "CmpItemKindOperator"},
CmpItemKindSnippet = {fg = "#FFFFFF", bg = "#DB8FFF"},
BlinkCmpKindSnippet = {link = "CmpItemKindSnippet"},
CmpItemKindText = {fg = "#FFFFFF", bg = "#6C6AEC"},
BlinkCmpKindText = {link = "CmpItemKindText"},
CmpItemKindVariable = {fg = "#FFFFFF", bg = "#E4A6F7"},
BlinkCmpKindConstant = {link = "CmpItemKindVariable"},
BlinkCmpKindEnumMember = {link = "CmpItemKindVariable"},
BlinkCmpKindField = {link = "CmpItemKindVariable"},
BlinkCmpKindProperty = {link = "CmpItemKindVariable"},
BlinkCmpKindReference = {link = "CmpItemKindVariable"},
BlinkCmpKindValue = {link = "CmpItemKindVariable"},
BlinkCmpKindVariable = {link = "CmpItemKindVariable"},
CmpItemKindConstant = {link = "CmpItemKindVariable"},
CmpItemKindEnumMember = {link = "CmpItemKindVariable"},
CmpItemKindField = {link = "CmpItemKindVariable"},
CmpItemKindProperty = {link = "CmpItemKindVariable"},
CmpItemKindReference = {link = "CmpItemKindVariable"},
CmpItemKindValue = {link = "CmpItemKindVariable"},
CmpItemMenu = {fg = "#E9D0F1", italic = true},
BlinkCmpLabelDescription = {link = "CmpItemMenu"},
BlinkCmpLabelDetail = {link = "CmpItemMenu"},
BlinkCmpSource = {link = "CmpItemMenu"},
BlinkCmpDoc = {link = "CmpNormal"},
BlinkCmpMenu = {link = "CmpNormal"},
BlinkCmpSignatureHelp = {link = "CmpNormal"},
CmpSel = {fg = "#FFFFFF", bg = "#7A6EBF", bold = true},
BlinkCmpMenuSelection = {link = "CmpSel"},
ColorColumn = {bg = "#2E2A37"},
Comment = {fg = "#7E7490", bold = true, italic = true},
BlinkCmpGhostText = {link = "Comment"},
IblWhitespace = {link = "Comment"},
LspInlayHint = {link = "Comment"},
RenderMarkdownHtmlComment = {link = "Comment"},
Conceal = {fg = "#7CF89B", bg = "#3B355F"},
Constant = {fg = "#2CEDC0"},
DapUIValue = {link = "Constant"},
NavicIconsConstant = {link = "Constant"},
CurSearch = {fg = "#25213B", bg = "#EAB9F9"},
Cursor = {fg = "#25213B", bg = "#EDE7FE"},
CursorColumn = {bg = "#2E2A37"},
CursorLine = {bg = "#3B355F"},
BlinkCmpDocCursorLine = {link = "CursorLine"},
NeoTreeCursorLine = {link = "CursorLine"},
CursorLineNC = {bg = "#2F2A4B"},
CursorLineNr = {fg = "#EDE7FE"},
CursorLineNrNC = {fg = "#EDE7FE"},
DapBreakpoint = {fg = "#FFB433"},
DapBreakpointCondition = {link = "DapBreakpoint"},
DapLogPoint = {link = "DapBreakpoint"},
DapUIPlayPause = {link = "DapBreakpoint"},
DapUIRestart = {link = "DapBreakpoint"},
DapBreakpointRejected = {fg = "#F2637E"},
DapStopped = {fg = "#FF8C57"},
DapUIStop = {link = "DapStopped"},
DapUIBreakpointsCurrentLine = {fg = "#2CD9ED", bold = true},
DapUICurrentFrameName = {link = "DapUIBreakpointsCurrentLine"},
DapUIBreakpointsDisabledLine = {fg = "#DED3FD"},
DapUIBreakpointsInfo = {fg = "#2CD9ED"},
DapUIBreakpointsPath = {fg = "#2CEDC0"},
DapUIDecoration = {fg = "#7CF89B"},
DapUIFrameName = {fg = "#EDE7FE"},
DapUILineNumber = {fg = "#FFDFA8"},
DapUIBreakpointsLine = {link = "DapUILineNumber"},
DapUIModifiedValue = {fg = "#2CEDC0", bold = true},
DapUIStepBack = {fg = "#2CEDC0"},
DapUIStepInto = {fg = "#2CEDC0"},
DapUIStepOut = {fg = "#2CEDC0"},
DapUIStepOver = {fg = "#2CEDC0"},
DapUIStoppedThread = {fg = "#7CF89B", undercurl = true},
DapUIThread = {fg = "#7CF89B"},
DapUIUnavailable = {fg = "#DED3FD"},
DapUIWatchesEmpty = {fg = "#FF8093"},
DapUIWatchesError = {fg = "#F2637E"},
DapUIWatchesValue = {fg = "#B68FFF"},
DapUIWinSelect = {fg = "#2CEDC0", bold = true},
Delimiter = {fg = "#AFAFDF"},
DiffAdd = {bg = "#313F54"},
["@text.diff.add"] = {link = "DiffAdd"},
DiffAddBright = {fg = "#8BF9A6"},
GitSignsAdd = {link = "DiffAddBright"},
GitSignsAddPreview = {link = "DiffAddBright"},
NvimTreeGitNew = {link = "DiffAddBright"},
DiffChange = {bg = "#272745"},
DiffChangeBright = {fg = "#FFD68F"},
GitSignsChange = {link = "DiffChangeBright"},
GitSignsChangePreview = {link = "DiffChangeBright"},
NvimTreeGitDirty = {link = "DiffChangeBright"},
DiffDelete = {fg = "#4C425C"},
["@text.diff.delete"] = {link = "DiffDelete"},
DiffDeleteBright = {fg = "#F58095"},
GitSignsDelete = {link = "DiffDeleteBright"},
GitSignsDeletePreview = {link = "DiffDeleteBright"},
NvimTreeGitDeleted = {link = "DiffDeleteBright"},
DiffText = {bg = "#2D2B69"},
DiffTextBright = {fg = "#8FC5FF"},
FylerGitStaged = {link = "DiffTextBright"},
NeoTreeGitStaged = {link = "DiffTextBright"},
NvimTreeGitStaged = {link = "DiffTextBright"},
Directory = {fg = "#DBCAFC"},
EndOfBuffer = {fg = "#2E2A37"},
DapUIEndofBuffer = {link = "EndOfBuffer"},
Error = {fg = "#463E6F", bg = "#F47189"},
ErrorMsg = {fg = "#FFFFFF", bg = "#F47189"},
FlashBackdrop = {bg = "#2D2848"},
FlashCurrent = {fg = "#3B355F", bg = "#EAB9F9"},
FlashCursor = {fg = "#3B355F", bg = "#40C4C4"},
FlashLabel = {fg = "#3B355F", bg = "#FFD080"},
FlashMatch = {fg = "#EEE5FF", bg = "#9579E6"},
FlashPrompt = {fg = "#EEE5FF", bg = "#9487F8"},
FlashPromptIcon = {fg = "#EEE5FF", bg = "#9487F8"},
FloatBorder = {fg = "#4C425C"},
DapUIFloatBorder = {link = "FloatBorder"},
FylerBorder = {link = "FloatBorder"},
ToggleTerm1FloatBorder = {link = "FloatBorder"},
ToggleTermFloatBorder = {link = "FloatBorder"},
FoldColumn = {fg = "#8876A7"},
Folded = {fg = "#8876A7", bg = "#2E2A37", bold = true},
Function = {fg = "#9CF2DE"},
NavicIconsConstructor = {link = "Function"},
NavicIconsFunction = {link = "Function"},
NavicIconsMethod = {link = "Function"},
FylerFSLink = {fg = "#CECDF3"},
FylerGreen = {fg = "#7CF89B"},
FylerGrey = {fg = "#DED3FD"},
FylerRed = {fg = "#F2637E"},
FylerYellow = {fg = "#FFD080"},
GitConflictAncestor = {bg = "#324362"},
AvanteConflictAncestor = {link = "GitConflictAncestor"},
GitConflictAncestorLabel = {bg = "#476294"},
AvanteConflictAncestorLabel = {link = "GitConflictAncestorLabel"},
GitConflictCurrent = {bg = "#393262"},
AvanteConflictCurrent = {link = "GitConflictCurrent"},
GitConflictCurrentLabel = {bg = "#534794"},
AvanteConflictCurrentLabel = {link = "GitConflictCurrentLabel"},
GitConflictIncoming = {bg = "#326259"},
AvanteConflictIncoming = {link = "GitConflictIncoming"},
GitConflictIncomingLabel = {bg = "#479486"},
AvanteConflictIncomingLabel = {link = "GitConflictIncomingLabel"},
GitSignsCurrentLineBlame = {fg = "#BEABF7"},
SnacksIndent = {link = "IblIndent"},
IblScope = {fg = "#D4B9EF"},
SnacksIndentScope = {link = "IblScope"},
SnacksIndentBlank = {link = "IblWhitespace"},
Identifier = {fg = "#EBEBFF"},
DapUIVariable = {link = "Identifier"},
NavicIconsEnumMember = {link = "Identifier"},
NavicIconsField = {link = "Identifier"},
NavicIconsKey = {link = "Identifier"},
NavicIconsProperty = {link = "Identifier"},
NavicIconsVariable = {link = "Identifier"},
NavicText = {link = "Identifier"},
Special = {link = "Identifier"},
IncSearch = {fg = "#FFFFFF", bg = "#DB8FFF", underline = true},
LineNr = {fg = "#8876A7"},
LocListCursorLine = {bg = "#384375"},
LocListCursorLineNC = {bg = "#1C2340"},
LocListNormal = {fg = "#EDE7FE", bg = "#242C4C"},
LocListNormalNC = {fg = "#EDE7FE", bg = "#1F253D"},
LspReferenceText = {bg = "#463E6F"},
LspSignatureActiveParameter = {fg = "#AEACFB"},
BlinkCmpSignatureHelpActiveParameter = {link = "LspSignatureActiveParameter"},
MatchParen = {fg = "#2E2A37", bg = "#2CEDC0"},
ModeMsg = {fg = "#EDE7FE"},
MoreMsg = {fg = "#EDE7FE"},
MultipleCursorsCursor = {fg = "#211D34", bg = "#B5ABED"},
MultipleCursorsVisual = {bg = "#766CAC"},
NavicIconsNull = {fg = "#8876A7"},
NavicSeparator = {fg = "#9383AF"},
NeoTreeBufferNumber = {fg = "#8876A7"},
NeoTreeDirectoryIcon = {fg = "#D9CDEE"},
FylerFSDirectoryIcon = {link = "NeoTreeDirectoryIcon"},
NeoTreeDirectoryName = {fg = "#CEB6FB"},
FylerFSDirectoryName = {link = "NeoTreeDirectoryName"},
NeoTreeDotfile = {fg = "#C3C3F4"},
NeoTreeFileIcon = {fg = "#C7C6E1"},
NeoTreeFileName = {fg = "#C3C3F4"},
FylerFSFile = {link = "NeoTreeFileName"},
NeoTreeFileNameOpened = {fg = "#A5A4F4"},
NeoTreeFilterTerm = {fg = "#C3C3F4"},
NeoTreeGitAdded = {fg = "#CAFCD6"},
FylerGitAdded = {link = "NeoTreeGitAdded"},
NeoTreeGitConflict = {sp = "#F2637E", undercurl = true},
FylerGitConflict = {link = "NeoTreeGitConflict"},
NeoTreeGitDeleted = {fg = "#F8AAB8"},
FylerGitDeleted = {link = "NeoTreeGitDeleted"},
NeoTreeGitIgnored = {fg = "#AEADDB"},
FylerGitIgnored = {link = "NeoTreeGitIgnored"},
NeoTreeGitModified = {fg = "#FFDFA8"},
FylerGitModified = {link = "NeoTreeGitModified"},
NeoTreeGitUnstaged = {fg = "#FFD68F"},
FylerGitUnstaged = {link = "NeoTreeGitUnstaged"},
NeoTreeGitUntracked = {fg = "#FFECCC"},
FylerGitUntracked = {link = "NeoTreeGitUntracked"},
NeoTreeHiddenByName = {fg = "#AEADDB"},
NeoTreeIndentMarker = {fg = "#8876A7"},
FylerIndentMarker = {link = "NeoTreeIndentMarker"},
NeogitCursorLine = {nocombine = true},
NeogitDiffAdd = {bg = "#355A59"},
NeogitDiffAddCursor = {bg = "#357E5D"},
NeogitDiffAddHighlight = {bg = "#35695A"},
NeogitDiffDelete = {bg = "#593153"},
NeogitDiffDeleteCursor = {bg = "#7B3257"},
NeogitDiffDeleteHighlight = {bg = "#673255"},
NeogitHunkHeader = {fg = "#DED3FD", bg = "#3B3465"},
NeogitHunkHeaderCursor = {fg = "#EEE5FF", bg = "#7064B4"},
NeogitHunkHeaderHighlight = {fg = "#EEE5FF", bg = "#534794"},
NoiceCmdlinePopupTitle = {fg = "#C3C3E5"},
NoiceCmdlineIcon = {link = "NoiceCmdlinePopupTitle"},
NonText = {fg = "#4C425C"},
IblIndent = {link = "NonText"},
NormalFloat = {fg = "#EDE7FE", bg = "#25213B"},
DapUIFloatNormal = {link = "NormalFloat"},
NormalFloatNC = {fg = "#EDE7FE", bg = "#211D34"},
NormalNC = {fg = "#EDE7FE", bg = "#1D1A2E"},
QFListNormalNC = {link = "NormalNC"},
Number = {fg = "#FF9A6B"},
Float = {link = "Number"},
NavicIconsNumber = {link = "Number"},
NvimTreeExecFile = {bold = true, italic = true},
NvimTreeFolderName = {fg = "#AB9FDB"},
NvimTreeEmptyFolderName = {link = "NvimTreeFolderName"},
NvimTreeGitMerge = {fg = "#B68FFF"},
NvimTreeGitRenamed = {fg = "#FF9A6B"},
FylerGitRenamed = {link = "NvimTreeGitRenamed"},
NvimTreeIndentMarker = {fg = "#6C5A8C"},
NvimTreeNormal = {fg = "#D9D7E5", bg = "#27223F"},
FylerNormal = {link = "NvimTreeNormal"},
NvimTreeNormalNC = {fg = "#D9D7E5", bg = "#1D1A2E"},
FylerNormalNC = {link = "NvimTreeNormalNC"},
NvimTreeOpenedFolderName = {fg = "#D2CAF2"},
NvimTreeOpenedHL = {fg = "#D4BDFF", bg = "#27223F"},
NvimTreeSpecialFile = {bold = true},
Pmenu = {fg = "#EDE7FE", bg = "#584F8C"},
PmenuSbar = {fg = "#EDE7FE", bg = "#584F8C"},
BlinkCmpScrollBarGutter = {link = "PmenuSbar"},
PmenuSel = {fg = "#2CEDC0", bg = "#8876A7"},
PmenuThumb = {fg = "#F4DBFF", bg = "#8279B4"},
BlinkCmpScrollBarThumb = {link = "PmenuThumb"},
Define = {link = "PreProc"},
Include = {link = "PreProc"},
Macro = {link = "PreProc"},
PreCondit = {link = "PreProc"},
QFListCursorLine = {bg = "#563875"},
QFListCursorLineNC = {bg = "#2D1C40"},
Question = {fg = "#EDE7FE"},
RenderMarkdownBullet = {fg = "#CECEF8"},
RenderMarkdownCode = {bg = "#2A244C"},
RenderMarkdownCodeInline = {bg = "#4B4186"},
RenderMarkdownDash = {fg = "#676798"},
RenderMarkdownError = {fg = "#F58095"},
RenderMarkdownH1 = {fg = "#FFFFFF", bold = true},
RenderMarkdownH1Bg = {fg = "#FFFFFF", bg = "#825FC4", bold = true},
RenderMarkdownH2 = {fg = "#E7DBFF", bold = true},
RenderMarkdownH2Bg = {fg = "#E7DBFF", bg = "#32305F", bold = true},
RenderMarkdownH3 = {fg = "#D4C2FA", bold = true},
RenderMarkdownH3Bg = {fg = "#D4C2FA", bg = "#2B2749", bold = true},
RenderMarkdownH4 = {fg = "#D4C2FA", bold = true},
RenderMarkdownH4Bg = {fg = "#D4C2FA", bg = "#282442", bold = true},
RenderMarkdownH5 = {fg = "#D4C2FA"},
RenderMarkdownH5Bg = {fg = "#D4C2FA", bg = "#282442"},
RenderMarkdownH6 = {fg = "#D4C2FA"},
RenderMarkdownH6Bg = {fg = "#D4C2FA", bg = "#282442"},
RenderMarkdownHint = {fg = "#9EA8FF"},
RenderMarkdownInfo = {fg = "#43EFC7"},
RenderMarkdownInlineHighlight = {bg = "#416586"},
RenderMarkdownLink = {fg = "#9EA8FF", underline = true},
RenderMarkdownWikiLink = {link = "RenderMarkdownLink"},
RenderMarkdownMath = {fg = "#9EA8FF", italic = true},
RenderMarkdownQuote = {fg = "#9EA8FF"},
RenderMarkdownSign = {fg = "#676798"},
RenderMarkdownSuccess = {fg = "#7CF89B"},
RenderMarkdownTableFill = {bg = "#25213B"},
RenderMarkdownTableHead = {fg = "#8185DA"},
RenderMarkdownTableRow = {link = "RenderMarkdownTableHead"},
RenderMarkdownUnchecked = {fg = "#8591FF"},
RenderMarkdownWarn = {fg = "#FFD68F"},
Search = {fg = "#EAB9F9"},
CmpItemAbbrMatch = {link = "Search"},
CmpItemAbbrMatchFuzzy = {link = "Search"},
TelescopeMatching = {link = "Search"},
SignColumn = {fg = "#2E2A37"},
SpecialChar = {fg = "#FF9A6B"},
SpecialComment = {fg = "#EDE7FE"},
SpecialKey = {fg = "#8876A7"},
SpellBad = {undercurl = true},
SpellCap = {undercurl = true},
SpellLocal = {undercurl = true},
SpellRare = {undercurl = true},
Statement = {fg = "#BDA5EE"},
Conditional = {link = "Statement"},
Exception = {link = "Statement"},
Keyword = {link = "Statement"},
Label = {link = "Statement"},
NavicIconsFile = {link = "Statement"},
NavicIconsOperator = {link = "Statement"},
Operator = {link = "Statement"},
PreProc = {link = "Statement"},
Repeat = {link = "Statement"},
StatusLine = {fg = "#4C425C", bg = "#211D34"},
StatusLineNC = {link = "StatusLine"},
StatusLineTerm = {link = "StatusLine"},
WinBar = {link = "StatusLine"},
StatusLineTermNC = {link = "StatusLineNC"},
WinBarNC = {link = "StatusLineNC"},
String = {fg = "#DBFFB3"},
Character = {link = "String"},
NavicIconsString = {link = "String"},
RenderMarkdownChecked = {link = "String"},
TabLine = {fg = "#EDE7FE", bg = "#2E2A37"},
TabLineFill = {fg = "#EDE7FE", bg = "#2E2A37"},
TabLineSel = {fg = "#2CEDC0", bg = "#8876A7"},
Tag = {fg = "#E9D0F1"},
DapUISource = {link = "Tag"},
TelescopePreviewBorder = {link = "TelescopeBorder"},
TelescopePromptBorder = {link = "TelescopeBorder"},
TelescopeResultsBorder = {link = "TelescopeBorder"},
TelescopePromptNormal = {link = "TelescopeNormal"},
TelescopePromptTitle = {fg = "#C3C3E5"},
TermCursorNC = {bg = "#2E2A37"},
Title = {fg = "#EDE7FE"},
Todo = {fg = "#FFD080"},
RenderMarkdownTodo = {link = "Todo"},
TreesitterContext = {bg = "#3E3861"},
TreesitterContextLineNumber = {fg = "#9383AF", bg = "#2D2848"},
Type = {fg = "#8FA9FF"},
DapUIScope = {link = "Type"},
DapUIType = {link = "Type"},
NavicIconsArray = {link = "Type"},
NavicIconsClass = {link = "Type"},
NavicIconsEnum = {link = "Type"},
NavicIconsEvent = {link = "Type"},
NavicIconsInterface = {link = "Type"},
NavicIconsModule = {link = "Type"},
NavicIconsNamespace = {link = "Type"},
NavicIconsObject = {link = "Type"},
NavicIconsPackage = {link = "Type"},
NavicIconsStruct = {link = "Type"},
NavicIconsTypeParameter = {link = "Type"},
StorageClass = {link = "Type"},
Structure = {link = "Type"},
Typedef = {link = "Type"},
TypeVirtualText = {fg = "#9EA8FF", bg = "#3E3861"},
Visual = {bg = "#584F8C"},
VisualNOS = {bg = "#4C425C"},
WarningMsg = {fg = "#2E2A37", bg = "#FFD080"},
WildMenu = {fg = "#2CEDC0", bg = "#2E2A37"},
WinSeparator = {fg = "#4C425C"},
VertSplit = {link = "WinSeparator"},
  -- PATCH_CLOSE
}

vim.cmd.highlight("clear")

vim.o.background = "dark"
vim.g.colors_name = "lavi"

for group, attrs in pairs(colors) do
  vim.api.nvim_set_hl(0, group, attrs)
end
