# Auto-generated by build.lua - do not edit manually
{
  background = "25213B";
  foreground = "EDE7FE";
  cursor-color = "EDE7FE";
  cursor-text = "25213B";
  selection-background = "584F8C";
  selection-foreground = "EDE7FE";
  palette = [
    "0=#2E2A37"
    "1=#E56179"
    "2=#6DE38B"
    "3=#F8C772"
    "4=#7C89F8"
    "5=#B09CED"
    "6=#33D7B0"
    "7=#EEE5FF"
    "8=#8876A7"
    "9=#ED788D"
    "10=#84EB9E"
    "11=#F9D494"
    "12=#8893FC"
    "13=#C09CF7"
    "14=#51E1C0"
    "15=#FFFFFF"
  ];
}
