# Auto-generated by build.lua - do not edit manually
{
  background = "25213B";
  foreground = "EDE7FE";
  cursor-color = "EDE7FE";
  cursor-text = "25213B";
  selection-background = "584F8C";
  selection-foreground = "EDE7FE";
  palette = [
    "0=#2E2A37"
    "1=#F2637E"
    "2=#7CF89B"
    "3=#FFD080"
    "4=#7583FF"
    "5=#B98AFF"
    "6=#2CEDC0"
    "7=#EEE5FF"
    "8=#8876A7"
    "9=#F47189"
    "10=#8BF9A6"
    "11=#FFD68F"
    "12=#8591FF"
    "13=#BF94FF"
    "14=#43EFC7"
    "15=#FFFFFF"
  ];
}
